<a href="https://colab.research.google.com/github/Sita-Personal/collection/blob/main/Pthon/Class1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print ("Sita"+"1")

Sita1


In [ ]:
leng= input("Enter Length ")
brth= input("Enter Bredth ")
print("Area= ",int(leng)*int(brth))
print("Perimeter= ", 2*(int(leng)+int(brth)))

Enter Length 12
Enter Bredth 56
Area=  672
Perimeter=  136


In [ ]:
number=35

if number%2==0:
  print ("Even")
else if:
  print("Odd")


Odd


In [ ]:
shop=["Milk","Eggs","Bread","Fruits","Vegetables"]
itm = input("Enter item ")

if itm.upper() in shop.upper():
  print("available")
else:
  print("not avaialbel")


Enter item eggs


AttributeError: 'list' object has no attribute 'upper'

In [ ]:

def Name(a="Sita", b="jena"):
    return (a+" "+b)
Name()




'Sita jena'

In [ ]:

def Multi(a: int, b: int , c: int ):
    return a * b * c
       # Output: 1
Multi(2, 3, 4)

24

In [ ]:
def Multi(a: int, b: int , c: int ):
    return a * b * c
       # Output: 1
Multi(2, 3, 4)

In [ ]:
def greatest(a: int, b: int, c: int):
    if a >= b and a >= c:
        print("Greatest:", a)
    elif b >= a and b >= c:
        print("Greatest:", b)
    else:
        print("Greatest:", c)

greatest(2, 3, 4)

Greatest: 4


In [ ]:
def evenodd(a: int) :
    if a % 2 == 0 :
        print("Even:", a)

    else:
        print("Odd:", a)

evenodd(12)

Even: 12


In [ ]:
class Fruit:
    def _init(self):
        self.name = input("Enter Fruit Name: ")
        self.price = float(input("Enter Price: "))
        self.quantity = int(input("Enter Quantity: "))

    def display_data(self):
        print("Fruit Name :", self.name)
        print("Price      :", self.price)
        print("Quantity   :", self.quantity)


   display_data()


In [ ]:
class Student:

   def __init__(self):
     self.name="Sita"
     self.marks=10

class child (Student)

  def display(self):
   print(self.name,self.marks)

  obj = child ()
  obj=display()


SyntaxError: expected ':' (3005934962.py, line 6)

In [ ]:
class Product:
    def __init__(self):
        self.Pr_name = "Prod-1"


class Child(Product):
    def __init__(self):
        super().__init__()
        self.weight = "3"


class Child2(Child):
    def __init__(self):
        super().__init__()
        self.price = "$20"

    def display(self):
        print(self.Pr_name, self.weight, self.price)


obj = Child2()
obj.display()

Prod-1 3 $20


In [ ]:
class ComputerScience:

        self.marks = int(input("Enter Computer Science Marks: "))

    def display(self):
        print("Student Name :", self.name)
        print("Computer Science Marks :", self.marks)


class English:
    def __init__(self):
        self.name = input("Enter Student Name: ")
        self.marks = int(input("Enter English Marks: "))

    def display(self):
        print("Student Name :", self.name)
        print("English Marks :", self.marks)


obj1 = ComputerScience()
obj1.display()

obj2 = English()
obj2.display()

In [ ]:
create an array using list with different float values
create an array using zeros with 5 rows and 7 columns
create an array using ones with 4 rows and 2 columns
create an array using full with 5 rows and 7 columns and number as 33.22
create an array using linspace with equal spacing of 2
create an array using arange with 4 as step size
create an array using random with 25 elements
create an array using randint with integer between 0 and 10

In [ ]:
import numpy as np
arr = np.array([1.5,2.75, 3.14,4.0,5.99])
print(arr)

import numpy as np
arr = np.zeros((5, 7))
print(arr)

import numpy as np
arr = np.ones((4, 2))
print(arr)

import numpy as np
arr = np.full((5,7),33.22)
print(arr)


import numpy as np
arr = np.linspace(0, 10, 6)
print(arr)

import numpy as np
arr2 = np.arange(0, 25, 4)
print(arr2)

import numpy as np
arr3 = np.random.random(25)
print(arr3)

import numpy as np
arr4 = np.random.randint(0, 11, 25)
print(arr4)

[1.5  2.75 3.14 4.   5.99]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[33.22 33.22 33.22 33.22 33.22 33.22 33.22]
 [33.22 33.22 33.22 33.22 33.22 33.22 33.22]
 [33.22 33.22 33.22 33.22 33.22 33.22 33.22]
 [33.22 33.22 33.22 33.22 33.22 33.22 33.22]
 [33.22 33.22 33.22 33.22 33.22 33.22 33.22]]
[ 0.  2.  4.  6.  8. 10.]
[ 0  4  8 12 16 20 24]
[0.72701602 0.49287499 0.04734721 0.890229   0.04195099 0.244144
 0.22876256 0.90381628 0.87932518 0.73550426 0.19351931 0.69145814
 0.005979   0.19550275 0.66507024 0.76626513 0.19409445 0.32379917
 0.89383262 0.40264241 0.19607847 0.79897935 0.39627788 0.10231619
 0.82273574]
[ 9  0  3  7  2  5  5  9 10  0  0  2  2  5  4  9  4  6  6 10  3  4  1  3
  6]
